resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.7.3/quick-start-minimal.yaml

patches:
  - path: patch-controller.yaml
    target:
      kind: Deployment
      name: workflow-controller
      namespace: argo
  - path: patch-server.yaml
    target:
      kind: Deployment
      name: argo-server
      namespace: argo
