apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/quickpizza

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: stress
          kubernetes.io/hostname: ultrap3
    target:
      kind: Deployment

  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment

  # Hot path services
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "10"
            memory: "6Gi"
          limits:
            cpu: "32"
            memory: "16Gi"
    target:
      kind: Deployment
      name: quickpizza-public-api

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "8"
            memory: "6Gi"
          limits:
            cpu: "32"
            memory: "16Gi"
    target:
      kind: Deployment
      name: quickpizza-catalog

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "4"
            memory: "6Gi"
          limits:
            cpu: "32"
            memory: "16Gi"
    target:
      kind: Deployment
      name: quickpizza-copy

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "6"
            memory: "6Gi"
          limits:
            cpu: "32"
            memory: "16Gi"
    target:
      kind: Deployment
      name: quickpizza-recommendations

  # Minimal services
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
    target:
      kind: Deployment
      name: quickpizza-grpc

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
    target:
      kind: Deployment
      name: quickpizza-config

  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
    target:
      kind: Deployment
      name: quickpizza-ws

  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: stress
          kubernetes.io/hostname: ultrap3
      - op: replace
        path: /spec/volumeClaimTemplates
        value: []
      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: data
            emptyDir: {}
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "1"
            memory: "4Gi"
          limits:
            cpu: "6"
            memory: "6Gi"
    target:
      kind: StatefulSet
