apiVersion: v1
kind: ServiceAccount
metadata:
  name: stress-sa
  namespace: stress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-executor
  namespace: stress
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-executor-binding
  namespace: stress
subjects:
- kind: ServiceAccount
  name: stress-sa
  namespace: stress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-executor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stress-quickpizza-manager
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "secrets", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stress-quickpizza-manager-binding
subjects:
- kind: ServiceAccount
  name: stress-sa
  namespace: stress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: stress-quickpizza-manager
