apiVersion: v1
kind: ServiceAccount
metadata:
  name: stress-sa
  namespace: stress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-executor
  namespace: stress
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflowtaskresults"]
  verbs: ["create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-executor-binding
  namespace: stress
subjects:
- kind: ServiceAccount
  name: stress-sa
  namespace: stress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-executor

