apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: io-rand-seq
  namespace: stress
spec:
  serviceAccountName: stress-sa
  ttlStrategy:
    secondsAfterCompletion: 300
    secondsAfterSuccess: 300
    secondsAfterFailure: 3600
  entrypoint: suite

  templates:
  - name: cooldown
    suspend:
      duration: 5m

  - name: suite
    steps:
    - - name: seq-write-12g-10m-55mbps
        templateRef:
          name: io-stress
          template: io-stress-container
        arguments:
          parameters:
          - { name: image,         value: ghcr.io/vlanx/io-stress:latest }
          - { name: mode,          value: "seq-write" }
          - { name: runtime_sec,   value: "600" }
          - { name: numjobs,       value: "1" }
            #- { name: file_size_gb,  value: "12" }
          - { name: test_dir,      value: "/scratch" }
          - { name: filename,      value: "fio_rand.dat" }
          - { name: block_size,    value: "1M" }
          - { name: iodepth,       value: "64" }
          - { name: target_mbps,   value: "55" } # Best when its sequential
          #- { name: target_iops,   value: "50" }
          - { name: host_path,     value: "/var/lib/module-stresser" }
          - { name: display,       value: "io-seq-write-12g-10m-55mbps" }
          ### CPU Requests/Limits for when we want more workers/cores
          - { name: cpu_req, value: "1" }
          - { name: cpu_lim, value: "1" }
          - { name: mem_req, value: "512Mi" }
          - { name: mem_lim, value: "512Mi" }

    - - name: cooldown-1
        template: cooldown

    - - name: seq-write-12g-10m-110mbps
        templateRef:
          name: io-stress
          template: io-stress-container
        arguments:
          parameters:
          - { name: image,         value: ghcr.io/vlanx/io-stress:latest }
          - { name: mode,          value: "seq-write" }
          - { name: runtime_sec,   value: "600" }
          - { name: numjobs,       value: "1" }
            #- { name: file_size_gb,  value: "12" }
          - { name: test_dir,      value: "/scratch" }
          - { name: filename,      value: "fio_rand.dat" }
          - { name: block_size,    value: "1M" }
          - { name: iodepth,       value: "64" }
          - { name: target_mbps,   value: "110" } # Best when its sequential
          #- { name: target_iops,   value: "50" }
          - { name: host_path,     value: "/var/lib/module-stresser" }
          - { name: display,       value: "io-seq-write-12g-10m-110mbps" }
          ### CPU Requests/Limits for when we want more workers/cores
          - { name: cpu_req, value: "1" }
          - { name: cpu_lim, value: "1" }
          - { name: mem_req, value: "512Mi" }
          - { name: mem_lim, value: "512Mi" }

    - - name: cooldown-2
        template: cooldown

    - - name: seq-write-12g-10m-166mbps
        templateRef:
          name: io-stress
          template: io-stress-container
        arguments:
          parameters:
          - { name: image,         value: ghcr.io/vlanx/io-stress:latest }
          - { name: mode,          value: "seq-write" }
          - { name: runtime_sec,   value: "600" }
          - { name: numjobs,       value: "1" }
            #- { name: file_size_gb,  value: "12" }
          - { name: test_dir,      value: "/scratch" }
          - { name: filename,      value: "fio_rand.dat" }
          - { name: block_size,    value: "1M" }
          - { name: iodepth,       value: "64" }
          - { name: target_mbps,   value: "166" } # Best when its sequential
          #- { name: target_iops,   value: "50" }
          - { name: host_path,     value: "/var/lib/module-stresser" }
          - { name: display,       value: "io-seq-write-12g-10m-166mbps" }
          ### CPU Requests/Limits for when we want more workers/cores
          - { name: cpu_req, value: "1" }
          - { name: cpu_lim, value: "1" }
          - { name: mem_req, value: "512Mi" }
          - { name: mem_lim, value: "512Mi" }

    - - name: cooldown-3
        template: cooldown

    - - name: seq-write-12g-10m-221mbps
        templateRef:
          name: io-stress
          template: io-stress-container
        arguments:
          parameters:
          - { name: image,         value: ghcr.io/vlanx/io-stress:latest }
          - { name: mode,          value: "seq-write" }
          - { name: runtime_sec,   value: "600" }
          - { name: numjobs,       value: "1" }
            #- { name: file_size_gb,  value: "12" }
          - { name: test_dir,      value: "/scratch" }
          - { name: filename,      value: "fio_rand.dat" }
          - { name: block_size,    value: "1M" }
          - { name: iodepth,       value: "64" }
          - { name: target_mbps,   value: "221" } # Best when its sequential
          #- { name: target_iops,   value: "50" }
          - { name: host_path,     value: "/var/lib/module-stresser" }
          - { name: display,       value: "io-seq-write-12g-10m-221mbps" }
          ### CPU Requests/Limits for when we want more workers/cores
          - { name: cpu_req, value: "1" }
          - { name: cpu_lim, value: "1" }
          - { name: mem_req, value: "512Mi" }
          - { name: mem_lim, value: "512Mi" }

    - - name: cooldown-4
        template: cooldown

    - - name: rand-read-12g-10m-276mbps
        templateRef:
          name: io-stress
          template: io-stress-container
        arguments:
          parameters:
          - { name: image,         value: ghcr.io/vlanx/io-stress:latest }
          - { name: mode,          value: "seq-write" }
          - { name: runtime_sec,   value: "600" }
          - { name: numjobs,       value: "1" }
            #- { name: file_size_gb,  value: "12" }
          - { name: test_dir,      value: "/scratch" }
          - { name: filename,      value: "fio_rand.dat" }
          - { name: block_size,    value: "1M" }
          - { name: iodepth,       value: "64" }
          - { name: target_mbps,   value: "276" } # Best when its sequential
          #- { name: target_iops,   value: "50" }
          - { name: host_path,     value: "/var/lib/module-stresser" }
          - { name: display,       value: "io-seq-write-12g-10m-276mbps" }
          ### CPU Requests/Limits for when we want more workers/cores
          - { name: cpu_req, value: "1" }
          - { name: cpu_lim, value: "1" }
          - { name: mem_req, value: "512Mi" }
          - { name: mem_lim, value: "512Mi" }
