apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: network-upload-download
  namespace: stress
spec:
  serviceAccountName: stress-sa
  ttlStrategy:
    secondsAfterCompletion: 15
    secondsAfterSuccess: 15
    secondsAfterFailure: 3600
  entrypoint: suite

  templates:
  - name: cooldown
    suspend:
      duration: 15s

  - name: suite
    steps:
    - - name: tcp-upload-100mbit-30s
        templateRef:
          name: network-stress
          template: network-stress-container
        arguments:
          parameters:
            - { name: image,     value: ghcr.io/vlanx/network-stress:latest }
            - { name: display,   value: "net-tcp-dl-100mbit-30s" }
            - { name: server,    value: "xbox.av.it.pt" }   # <— your server
            - { name: proto,     value: "tcp" }
            - { name: direction, value: "upload" }
            - { name: bandwidth, value: "100" }            # Mbit/s
            - { name: time,      value: "30" }
            - { name: parallel,  value: "1" }
            - { name: zerocopy,  value: "1" }
            # resources
            - { name: cpu_req, value: "1" }
            - { name: cpu_lim, value: "1" }
            - { name: mem_req, value: "256Mi" }
            - { name: mem_lim, value: "256Mi" }

    - - name: cooldown-1
        template: cooldown

    - - name: tcp-download-100mbit-30s
        templateRef:
          name: network-stress
          template: network-stress-container
        arguments:
          parameters:
            - { name: image,     value: ghcr.io/vlanx/network-stress:latest }
            - { name: display,   value: "net-tcp-dl-100mbit-30s" }
            - { name: server,    value: "xbox.av.it.pt" }
            - { name: proto,     value: "tcp" }
            - { name: direction, value: "download" }
            - { name: bandwidth, value: "100" }
            - { name: time,      value: "30" }
            - { name: parallel,  value: "1" }
            - { name: zerocopy,  value: "1" }
            # resources
            - { name: cpu_req, value: "1" }
            - { name: cpu_lim, value: "1" }
            - { name: mem_req, value: "256Mi" }
            - { name: mem_lim, value: "256Mi" }
