apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/quickpizza

namespace: atnog-test5

patches: 
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: stress
          kubernetes.io/hostname: atnog-test5 
    target:
      kind: Deployment

  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          role: stress
          kubernetes.io/hostname: atnog-test5
      - op: replace
        path: /spec/volumeClaimTemplates
        value: []
      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: data
            emptyDir: {}
    target:
      kind: StatefulSet
